version: '3.8'

services:
  resumidor-videos:
    build: .
    container_name: resumidor-videos-youtube
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./temp:/app/temp
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Opcional: Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: resumidor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - resumidor-videos
    restart: unless-stopped
    profiles:
      - production

volumes:
  temp_data:
    driver: local
